# Generated by Django 3.1.7 on 2021-04-03 23:58

from django.db import migrations, models

import django_simple_timeseries.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BasicModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ts1",
                    django_simple_timeseries.models.TimeseriesField(
                        max_points=1440, resolution_seconds=60
                    ),
                ),
                (
                    "ts2",
                    django_simple_timeseries.models.TimeseriesField(
                        max_points=3, resolution_seconds=5
                    ),
                ),
            ],
        ),
    ]
